name       : kmag
version    : 17.12.3
release    : 3
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.3/src/kmag-17.12.3.tar.xz : 7ca8b5872832a9d0985daedb8f587b5057d7f569dee490b2a3d97c568beb2d59
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde
summary    : KMag is a screen magnifier
description: |
    KMag is a screen magnifier.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kxmlgui-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
