name       : kmag
version    : 18.08.2
release    : 10
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.2/src/kmag-18.08.2.tar.xz : 67bfdbaf1ff63624e15ef2394604e608c1dab2670f4255daf09e4bfca2ae70b0
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde
summary    : KMag is a screen magnifier
description: |
    KMag is a screen magnifier.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
