name       : kmag
version    : 19.08.1
release    : 21
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.1/src/kmag-19.08.1.tar.xz : 28504935665df18246cc6db4288dc2b33f24ed7114007df008f4310ce8792ceb
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : desktop.kde
summary    : KMag is a screen magnifier
description: |
    KMag is a screen magnifier.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
