name       : kmag
version    : 18.04.1
release    : 5
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.1/src/kmag-18.04.1.tar.xz : ed6daeff42306bc035db1f5088282db42c2d5347649a9817c47e76bbba027198
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde
optimize   : lto
summary    : KMag is a screen magnifier
description: |
    KMag is a screen magnifier.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
