name       : kmag
version    : 19.04.1
release    : 17
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.1/src/kmag-19.04.1.tar.xz : aa5ec91dcffc1a2f1037332aeacb096ab55388624c844c7fa311ca38a5e40874
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : desktop.kde
summary    : KMag is a screen magnifier
description: |
    KMag is a screen magnifier.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
