name       : kmag
version    : 17.12.2
release    : 2
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.2/src/kmag-17.12.2.tar.xz : a22b8c382f66574f83672aab005ff6aaf9fa110794936f8544a250438b27b07b
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde
summary    : KMag is a screen magnifier
description: |
    KMag is a screen magnifier.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kxmlgui-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
