name       : kmag
version    : 20.12.0
release    : 38
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.0/src/kmag-20.12.0.tar.xz : 0ade18c35210cd80827ba239a413343663f04efe9974efdf6fe2aa50a3549975
homepage   : https://kde.org/applications/utilities/org.kde.kmag
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : desktop.kde
summary    : KMag is a screen magnifier
description: |
    KMag is a screen magnifier.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
