name       : kmag
version    : 19.08.3
release    : 23
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.3/src/kmag-19.08.3.tar.xz : 216e5db763f72ff1f4ada339912dc686fa7a6cea0dafc8b9eab35601edabc950
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : desktop.kde
summary    : KMag is a screen magnifier
description: |
    KMag is a screen magnifier.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
